# test_path: ./data/benchmark/general/benchmark_id.csv
# corpus_path: ./data/benchmark/general/corpus.json
test_path: ./data/benchmark/edu/benchmark_id.csv
corpus_path: ./data/benchmark/edu/corpus_noise_large.json
model_path: ./runs/random
batch_size: 512
pooler: 'cls'
k: [5,10,20]
export_output: True
output_path : ./output